"""Add goal to sprint

Revision ID: 0b2cea9f32eb
Revises: 930d39853bf4
Create Date: 2025-05-05 15:40:57.502313

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0b2cea9f32eb'
down_revision = '930d39853bf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprint', sa.Column('goal', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sprint', 'goal')
    # ### end Alembic commands ###